/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MixerLazyImport = createFileRoute('/mixer')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MixerLazyRoute = MixerLazyImport.update({
  path: '/mixer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mixer.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/mixer': {
      id: '/mixer'
      path: '/mixer'
      fullPath: '/mixer'
      preLoaderRoute: typeof MixerLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/mixer': typeof MixerLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/mixer': typeof MixerLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/mixer': typeof MixerLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mixer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mixer'
  id: '__root__' | '/' | '/mixer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MixerLazyRoute: typeof MixerLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MixerLazyRoute: MixerLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mixer"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/mixer": {
      "filePath": "mixer.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
